language: python
python:
- 3.6
- 3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
- pip install -U tox-travis
- pip install -U codecov
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sentrip
  password:
    secure: J7/zFf/sLSNqJOZY0BxnuG3qT+GAOhLFW+0h+4mUi4HVXF1Nck6UYsJ/y9ejph2wLoacA42DL+YM1X3sKUMzEd8zCQ0ECzpuujQbf0CzhnkyKsFak8EDj++cxaXXoLiA27KQP+uXfO2C63HNtY5L2O7F9AYabheWDhGpnu9DYUmA5t4kwTSCJj/6Nbpv7UosdLkBNzGNt/+oRx61k7GoLeN3loSiPL28jR9D2mX4VtfRfReqdIt2pEV4Ywtc3tvmFoHWC2EkjE2XQkxk+K4fzy2njrWz0AIFkkT1vkETEWfMgYhUR8h+/SwdgLtheM3H5U4EUIN3Na+joqcd0ARZaAjfVoutTFPjnvFuxDCLWGc5KhdHzP08M7Oa5obWWZOcWWvKubjUDeIc/+UAtVKfrw/YsFTMgWjv4NMIpIOQoNpXTlZOw6Q5o4qbXTWDukIXhqIIfHgsVQRnx20v/h2LeG78T09tTqpMW+mXfJnnpW4gQQsQS8KJR4bvgQNmaMY/O7BSM5knt/dwSYXqcLTuA3O3wXhUJ2KmD/pq4Jw0FWpJHLdbA1BZuR6fkMCEtWoLmgl8XesSykyl1tp3xtIzN3DxkqaNl+PYLwdZ6ouzQtnmrTOypeev2PwJaZcB//Ar3bUvQOJg3zy4N1t8i/h+u+/g+GzKy/diIHsL+j6Xb3c=
  on:
    tags: true
    repo: sentrip/instatools
    python: 3.6
after_success: codecov -t edc12da8-a0fb-4780-88cd-faae8792364a
